### ISSUE TITLE
Changes tab under key About

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/ala-keys-ui#11]
The Changes tab under a key's About is no longer working - just gives a list of taxa. This is a useful tab reports changes that have been made to a key since it was uploaded) - please reinstate

**Comment by nielsklazenga** [comment]
This is not in SDD, so it will require a separate web service, as I don't think ALA Keys will support it.

I am not sure if I want it back in the same form, as I would like to explore proper revision history (which is very hard for pathway keys). 

So far, it has only been used by a single person.

**Comment by nielsklazenga** [comment]
I am going to put it back for now, by the way, but I'll leave the issue open.

**Comment by KevinThiele** [comment]
Yes by a single person, but a pretty important person!

The reason why it’s important is that we will increasingly need to manage uploaded keys, and tracking edits becomes important. Other users of KeyBase may well upload a key then just leave it alone, so they would have no use for this. I use it all the time for keeping critical historical information as to howe the key evolves and is edited over time. This will be very important in future, even though for many users it isn’t now.

**Comment by KevinThiele** [comment]
Thanks - great

**Comment by nielsklazenga** [comment]
I think that is in the eyes of the beholder.

My argument is not that revision management is not important, but that this is not the right way to do it.

**Comment by KevinThiele** [comment]
So what’s the right way?

**Comment by nielsklazenga** [comment]
I think I would like to store the old versions and then do a diff. This should give you the change note without actually having to write it down.

**Comment by KevinThiele** [comment]
Yes, the problem is that the change note may be more than just a diff – it’s useful sometimes to give a reason for the change, rather than just the bald change itself.

**Comment by nielsklazenga** [comment]
Let's do both then.

**Comment by nielsklazenga** [comment]
The change notes are back. It turned out it was only a typo that kept them out, but now the whole page comes from web services.

**Comment by KevinThiele** [comment]
Great - thanks
