### ISSUE TITLE
Keys list jumps back to Projects list after delete key

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/ala-keys-ui#12]
Go to a project's listing of keys. Delete a key. Instead of remaining on the keys list page, KeyBase jumps back to the Projects page.

**Comment by nielsklazenga** [comment]
Fixed. Only tried it out in DEV though, so let me know if it doesn't work in PRODUCTION.

**Comment by KevinThiele** [comment]
Better, but after deleting a key (from key list view) it now jumps back to key tree view - better to return to list view (may want to delete several keys) - best to return to the same place in the page

**Comment by nielsklazenga** [comment]
That is not standard behaviour when you go back to a page. KeyBase doesn't know if the key was deleted from the tree or from the list.

**Comment by KevinThiele** [comment]
But you can only delete from the list.

k

**Comment by nielsklazenga** [comment]
You can delete from the tree as well:
![image](https://cloud.githubusercontent.com/assets/4694550/13446719/ee63f84c-e069-11e5-81fe-515ea04f3c7e.png)

The point is, by the way, that the tree and the list are on the same page, in contrast to the previous version, where they were different pages.

**Comment by KevinThiele** [comment]
Good – I see now. Problem was simply that I hadn’t caught up that there was a right-click menu now.

**Comment by nielsklazenga** [comment]
Has been there all along.

**Comment by KevinThiele** [comment]
How could I have missed it?
