### ISSUE TITLE
Bug in local filter

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/ala-keys-ui#14]
Go to a key. Filter in Player view. Now change to bracketed view - KeyBase gets stuck

**Comment by nielsklazenga** [comment]
Yes, noticed that and reported it here: https://github.com/rbgvictoria/keybase/issues/2.

I think it is the separation of the loading of the interactive and other keys to make the interactive keys more responsive more quickly that I did last week that broke it.

**Comment by nielsklazenga** [comment]
I think I've fixed this now.
