### ISSUE TITLE
Non-logged-in users have access to Delete right-click menu

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/ala-keys-ui#15]
Users who are not logged in can right-click on an item in the keys tree and have access to Delete. They can't actually delete, but the menu option shouldn't be there.

**Comment by nielsklazenga** [comment]
Thanks, I noticed that too when I took that screenshot last week. Realised afterwards that I wasn't logged in and shouldn't have seen it. I have known for much longer that logged in users who do not have the right privileges can see the edit and delete options.
