### ISSUE TITLE
Viewing key notes at the head of the key

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/ala-keys-ui#20]
Occasionally, keys need or benefit from explanatory notes for a user. Currently we have two metadata fields for keys, Description and Notes; the latter is the appropriate field for such key notes. However, currently these are displayed on the About tab for a key, which will rarely be viewed by key users. I think it would be better for Notes to be displayed immediately under the key title and citation so users can be aware of them before starting the key.

**Comment by nielsklazenga** [comment]
Out of the question.
